name: Tests

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'

jobs:
  build_and_test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set up Poetry
        uses: Gr1N/setup-poetry@v4
        with:
          poetry-version: 1.1.0

      - name: Install dependencies
        run: make env
  
      - name: Run tests
        run: make test
